{% set name = "zappend" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7679f76627a8e66444e1774a456d30bd1ec1f20c71e9159e6a00a7d295be96e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - zappend = zappend.cli:zappend

requirements:
  host:
    - python >=3.10
    - setuptools >=40.9.0
    - pip
  run:
    - python >=3.10
    - click
    - dask-core
    - fsspec
    - jsonschema
    - numpy
    - pyyaml
    - xarray
    - zarr

test:
  imports:
    - zappend
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bcdev.github.io/zappend
  summary: Tool for creating and updating Zarr datacubes from smaller slices
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forman
    - pont-us
    - ruchimotwaniBC
    - TejasMorbagal
    - thomasstorm
    - TonioF
