{% set python_min = '3.10' %}
{% set name = "zappend" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec4f80fca8b36e1a442f007f1fd8d7fe792e1d741c267e595a5de95649a2fdd4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - zappend = zappend.cli:zappend

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.9.0
    - pip
  run:
    - python >={{ python_min }}
    - click
    - dask-core
    - fsspec
    - jsonschema
    - numcodecs
    - numpy
    - pyyaml
    - xarray
    - zarr

test:
  imports:
    - zappend
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://bcdev.github.io/zappend
  summary: Tool for creating and updating Zarr datacubes from smaller slices
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forman
    - pont-us
    - ruchimotwaniBC
    - TejasMorbagal
    - thomasstorm
    - TonioF
